steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: [
        "build",
        ".",
        "-t",
        "gcr.io/$PROJECT_ID/react-project:$SHORT_SHA", # Change "react-project" to your project name
        "-f",
        "Dockerfile",
        "--build-arg",
      ]

  # Push the Docker image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/react-project:$SHORT_SHA"] # Change "react-project" to your project name

  # Deploy the Docker image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "react-project" # Change "react-project" to your project name
      - "--region=${_REGION}" # Customize the region as needed
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--image=gcr.io/${PROJECT_ID}/react-project:$SHORT_SHA" # Change "react-project" to your project name
      - "--port=8080"

options:
  logging: CLOUD_LOGGING_ONLY
